name: Figma Icons

on:
  schedule:
    - cron: '* * * * *'

permissions:
  pull-requests: write
jobs:
  prepare:
    name: Prepare deps
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            **/node_modules
            ./node_modules
          key: ${{ runner.os }}-nm-${{ hashFiles('**/yarn.lock') }}
      - run: yarn install --production=false
      - run: cd ./scripts/figma && yarn install --production=false


  loadIcons:
    name: Load Icons
    runs-on: ubuntu-latest
    needs: [prepare]
    env:
      FIGMA_TOKEN: figd_NmoDnUqxNkAG58er2ALW5NJIEMkHzn3AgqIKvZP9

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            **/node_modules
            ./node_modules
          key: ${{ runner.os }}-nm-${{ hashFiles('**/yarn.lock') }}
      - run: yarn run figma:icons
      - uses: peter-evans/create-pull-request@v4.1.3
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          branch: figma/icons-${{ github.run_number }}
          commit-message: "figma: Автоматическая выгрузка иконок"
          title: "figma: Автоматическая выгрузка иконок"
          body: "Автоматическая выгрузка иконок из Figma"

